version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

formats: all

build:
  image: latest

python:
  version: 3.6
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
