version: 2

sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: false

formats:
-   htmlzip

build:
    os: ubuntu-20.04
    image: testing
    apt_packages:
    -   pandoc

python:
    version: 3.9
    install:
    -   method: pip
        path: .
        extra_requirements:
        -   docs
