version: 2

build:
    os: ubuntu-22.04
    tools:
        python: '3.10'

sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: false

python:
    install:
    -   method: pip
        path: .
        extra_requirements: [docs]

submodules:
    include: [docs/source/notebooks]
