name: Upload coverage to Codecov
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage
      run: |
        pip install .[test]
        python-vendorize "$GITHUB_WORKSPACE/vendorize.toml"
        pip install pytest-cov
        pytest --cov-config=.coveragerc --cov=./ --cov-report=xml
    - name: Upload coverage
      shell: bash
      if: ${{ success() }}
      run: |
        GITHUB_ACTION= bash <(curl -s https://codecov.io/bash) -X search -f "./coverage.xml"
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
