name: Deployment

on:
    push:
        branches: [master]
        tags: [v*]

jobs:
    deploy:
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        needs: [lint, test]
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
            with:
                fetch-depth: 0
        -   name: Set up Python 3.8
            uses: actions/setup-python@v2
            with:
                python-version: 3.8

        -   name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install build towncrier rstcheck
                pip install -e'.'

        -   name: Build a binary wheel and a source tarball
            run: |
                python -m build --sdist --wheel --outdir dist/

        -   name: Publish package on PyPI
            uses: pypa/gh-action-pypi-publish@master
            with:
                user: __token__
                password: ${{ secrets.PYPI_TOKEN }}
                skip_existing: true
                verbose: true
