name: Deployment
on:
  push:
    tags: [v*]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: deployment
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Build package
      run: tox -e build-package

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        verify-metadata: true
        verbose: true
