name: News

on:
    pull_request:
        branches: [master, dev]
        types: [closed]

jobs:
    # TODO(michalk8): once docs linting is up, use tox
    news:
        if: ${{ github.event.pull_request.merged }}
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
            with:
                token: ${{ secrets.TOWNCRIER_TOKEN }}
        -   name: Set up Python 3.8
            uses: actions/setup-python@v2
            with:
                python-version: 3.8

        -   name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install towncrier rstcheck requests
                pip install -e'.'
        -   name: Generate news fragment
            env:
                PR_NUMBER: ${{ github.event.number }}
            run: |
                python docs/source/create_news_fragment.py "$PR_NUMBER" -v
                rstcheck docs/source/release/changelog/*.rst

        -   name: Commit news fragment
            id: auto-commit-action
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
                commit_message: ${{ format('[auto][ci skip] Generate news fragment (#{0})', github.event.number) }}
                branch: ${{ github.base_ref }}
                file_pattern: docs/source/release/changelog/*.rst
                commit_user_name: CI
                skip_dirty_check: false

        -   name: Update dev release notes
            if: ${{ steps.auto-commit-action.outputs.changes_detected == 'true' && contains(github.base_ref, 'dev') }}
            run: |
                rm -f docs/source/release/notes-dev.rst
                towncrier build --yes --version dev
                rstcheck docs/source/release/notes-dev.rst

        -   name: Commit dev release notes
            if: ${{ steps.auto-commit-action.outputs.changes_detected == 'true' && contains(github.base_ref, 'dev') }}
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
                commit_message: ${{ format('[auto][ci skip] Update dev release notes (#{0})', github.event.number) }}
                branch: ${{ github.base_ref }}
                file_pattern: docs/source/release/notes-dev.rst
                commit_user_name: CI
                skip_dirty_check: false
