name: Build documentation when updating the notebooks
on: [repository_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Event information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: Trigger documentation build on ReadTheDocs
        if: github.event.action == 'build_docs'
        env:
          TOKEN: ${{ secrets.RTD_TOKEN }}
        run: |
          curl -X POST -d "branches=master" -d "token=$TOKEN" https://readthedocs.org/api/v2/webhook/cellrank/125510/
      - name: Report success
        if: ${{ success() }}
        run: |
          echo "Succesfully sent the request"
      - name: Report failure
        if: ${{ failure() }}
        run: |
          echo "Failed to send the request"
